# Generated by Django 5.2.8 on 2025-11-15 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('exclusive', 'Ексклюзивний реліз'), ('distribution', 'Дистрибуція альбому'), ('long_term', 'Довгострокова співпраця')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Активний'), ('expiring', 'Закінчується'), ('pending', 'На розгляді'), ('expired', 'Закінчився')], default='pending', max_length=20)),
                ('artist_royalty_percent', models.DecimalField(decimal_places=2, help_text='Процент для артиста', max_digits=5)),
                ('label_royalty_percent', models.DecimalField(decimal_places=2, help_text='Процент для лейблу', max_digits=5)),
                ('duration_months', models.PositiveIntegerField(help_text='Тривалість у місяцях')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Додаткові примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'label_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
