# Generated by Django 5.2.8 on 2025-11-15 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('trap', 'Trap'), ('lofi', 'Lo-Fi'), ('hiphop', 'Hip-Hop'), ('rock', 'Rock'), ('electronic', 'Electronic'), ('jazz', 'Jazz'), ('rnb', 'R&B'), ('pop', 'Pop')], max_length=20)),
                ('bpm', models.PositiveIntegerField(help_text='Beats per minute')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Ціна в доларах', max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='beats/')),
                ('plays_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True, help_text='Чи доступний біт для покупки')),
                ('is_exclusive', models.BooleanField(default=False, help_text='Ексклюзивний біт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(limit_choices_to={'role': 'producer'}, on_delete=django.db.models.deletion.CASCADE, related_name='beats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('active', 'Активна'), ('recording', 'Запис вокалу'), ('mixing', 'Зведення'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('producer_share', models.DecimalField(decimal_places=2, help_text='% продюсера', max_digits=5)),
                ('artist_share', models.DecimalField(decimal_places=2, help_text='% артиста', max_digits=5)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Додаткові примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='artist_collabs', to=settings.AUTH_USER_MODEL)),
                ('beat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.beat')),
                ('producer', models.ForeignKey(limit_choices_to={'role': 'producer'}, on_delete=django.db.models.deletion.CASCADE, related_name='producer_collabs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
